name: Deploy Pokémon GO Stats Viewer
on:
  registry_package:
    types:
      - published

jobs:
  deploy:
    name: Deploy Pokémon GO Stats Viewer
    runs-on: ubuntu-latest
    environment: production
    env:
      REMOTE_HOST: ${{ vars.REMOTE_HOST }}
      REMOTE_USER: ${{ vars.REMOTE_USER }}
      SSH_PORT: ${{ vars.REMOTE_PORT }}
    steps:
      - uses: actions/checkout@v7
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H -p "$SSH_PORT" "$REMOTE_HOST" >> ~/.ssh/known_hosts
      - name: Restart Docker compose
        run: |
          ssh -p $SSH_PORT -i ~/.ssh/id_ed25519 $REMOTE_USER@$REMOTE_HOST "
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
            cd /home/services/go-cp-stats-viewer
            docker compose down
            docker compose up -d --pull=always
          "

